/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ConvertidorUnidades;
import javax.swing.SpinnerNumberModel;
import javax.swing.DefaultComboBoxModel;
import java.awt.event.ItemEvent;
import java.text.DecimalFormat;
/**
 *
 * @author UTN
 */
public class Formulario_de_conversión_de_unidades extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Formulario_de_conversión_de_unidades.class.getName());

    private final ConvertidorUnidades.ConversorTemperatura converter = new ConvertidorUnidades.ConversorTemperatura();

private void calcular() {
    double valor = ((Number) jSpinner1.getValue()).doubleValue();
    Unidadtemperatura origen = (Unidadtemperatura) jComboBoxOrigen.getSelectedItem();
    Unidadtemperatura destino = (Unidadtemperatura) jComboBoxDestino.getSelectedItem();

    double resultado = converter.convertir(valor, origen, destino);
    jTextFieldResultado.setText(new DecimalFormat("#,##0.####").format(resultado));
}
    /**
     */
    public Formulario_de_conversión_de_unidades() {
    initComponents();
    calcular();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldResultado = new javax.swing.JTextField();
        jComboBoxOrigen = new javax.swing.JComboBox<>();
        jComboBoxDestino = new javax.swing.JComboBox<>();
        jButtonIntercambiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setText("Valor a convertir");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0.0, -1000000.0, 1000000.0, 0.5));
        jSpinner1.addChangeListener(this::jSpinner1StateChanged);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setText("Resultado");

        jTextFieldResultado.setEditable(false);

        jComboBoxOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(Unidadtemperatura.values()));
        jComboBoxOrigen.addItemListener(this::jComboBoxOrigenItemStateChanged);

        jComboBoxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(Unidadtemperatura.values()));
        jComboBoxDestino.addItemListener(this::jComboBoxDestinoItemStateChanged);

        jButtonIntercambiar.setFont(new java.awt.Font("Microsoft JhengHei UI", 3, 14)); // NOI18N
        jButtonIntercambiar.setText("Intercambiar");
        jButtonIntercambiar.addActionListener(this::jButtonIntercambiarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldResultado)
                                    .addComponent(jComboBoxDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jButtonIntercambiar)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonIntercambiar)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
          calcular();
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jComboBoxOrigenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxOrigenItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
        calcular();
    }
    }//GEN-LAST:event_jComboBoxOrigenItemStateChanged

    private void jComboBoxDestinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDestinoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
        calcular();
    }
    }//GEN-LAST:event_jComboBoxDestinoItemStateChanged

    private void jButtonIntercambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIntercambiarActionPerformed
        Unidadtemperatura origen = (Unidadtemperatura) jComboBoxOrigen.getSelectedItem();
    Unidadtemperatura destino = (Unidadtemperatura) jComboBoxDestino.getSelectedItem();

    jComboBoxOrigen.setSelectedItem(destino);
    jComboBoxDestino.setSelectedItem(origen);

    calcular();
    }//GEN-LAST:event_jButtonIntercambiarActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Formulario_de_conversión_de_unidades().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIntercambiar;
    private javax.swing.JComboBox<Unidadtemperatura> jComboBoxDestino;
    private javax.swing.JComboBox<Unidadtemperatura> jComboBoxOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextFieldResultado;
    // End of variables declaration//GEN-END:variables
}
